Gnome 45 support
bellini666/gnome-shell-notifications-alert pull request #60
Opened 2023-10-27 11:17 UTC by zweif

This works for me on Gnome 45 (Ubuntu 23.10).
Fixes #59

2023-11-02 20:58 UTC, bellini666 requested changes
I added suggestions for the pt_BR translations, as I'm brazilian =P

But for the other languages, probably it is better to remove the empty strings so at least the original english strings will be used

2023-11-02 20:58 UTC, bellini666 commented on src/locale/pt_BR.po
> +msgstr ""
```suggestion
msgstr "Cores"
```

2023-11-02 20:58 UTC, bellini666 commented on src/locale/pt_BR.po
> +msgstr "Lista do filtro"
```suggestion
msgid "Filter"
msgstr "Filtro"
```

2023-11-02 20:58 UTC, bellini666 commented on src/locale/pt_BR.po
> +msgstr ""
```suggestion
msgstr "Comportamento"
```

2023-11-03 08:20 UTC, zweif commented
It seems that my wording was misleading. If the translation contains an empty string, the original one is used instead. I wanted to say that the translations are incomplete. Removing the empty strings would likely interfere with tools for translation like Poedit.

Would you do the changes to pt_BR.po?

2023-11-03 21:44 UTC, bellini666 commented
Oh, I see. Didn't know that =P

Will merge this then the way it is and try to release a new version on ego :)

2023-11-03 21:45 UTC, merged