Update description and respect 'Do Not Disturb'
bellini666/gnome-shell-notifications-alert pull request #62
Opened 2023-11-16 00:00 UTC by zweif

The messaging menu is gone and so is the presence switch. This updates the description of the extension and uses the Gnome 'Do Not Disturb' setting instead of the presence status.
Fixes #54

2023-12-20 09:51 UTC, zweif commented
Hey @bellini666, could you take a look at this?

2023-12-20 23:14 UTC, bellini666 requested changes
OMG sorry for not seeing this earlier. Somehow I missed the notification for this.

TBH it is being a while since I don't use this extension anymore, so I'm going to trust you that this is working and doing what it is supposed to do :)

Just asked to revert some translations that were not updated and should be good to merge

2023-12-20 23:14 UTC, bellini666 commented on src/locale/cs_CZ.po
> +msgid "Alert even if you enable 'Do Not Disturb' (default: OFF)"
I prefer to revert the changes to those translations if they are not going to be updated

2023-12-20 23:14 UTC, bellini666 commented on src/locale/nl_NL.po
> +#, fuzzy
Ditto

2023-12-20 23:14 UTC, bellini666 commented on src/locale/pt_BR.po
> -msgid "Alert even if you set notifications to OFF on user menu (default: OFF)"
Ditto

2023-12-21 00:42 UTC, zweif commented
Thanks for looking at this. Do you mean the locale files shouldn't be changed if I cannot translate them properly? 
They were updated with the `make locale-files` command to reflect the changed strings in the code. The `fuzzy` annotation indicates that the annotated string might need some work (which they actually do). This is for example used by Poedit.

I agree that this should be translated properly, but I think leaving these files unchanged instead is not a good solution.
What we could do is
- keep the imperfect translations (as in this PR) and wait for someone to improve them later
- remove the imperfect translations (set empty strings) and wait for someone to add proper ones later
- use some tool like deepl to improve them now - but I cannot really verify the output
- maybe ask previous translators to do it - you could do pt_BR

What do you think?

2023-12-21 12:49 UTC, bellini666 commented
@zweif Hrmmm I see what you mean. Yeah, I think removing the `fuzzy` and setting those translations to an empty string so the original english string will be used is the best option.

And yes, I can do pt_BR right after this is merged :)

2023-12-22 13:33 UTC, zweif commented
@bellini666 I removed the fuzzy strings in cs_CZ.po and nl_NL.po. There were more than expected. Now only pt_BR.po is left :)

2023-12-22 14:44 UTC, bellini666 approved these changes
Ty!

2023-12-22 14:44 UTC, merged

2023-12-22 14:49 UTC, bellini666 commented
Sent it to review: https://extensions.gnome.org/review/49579